# Generated by Django 4.1.3 on 2022-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
