# Generated by Django 4.1.3 on 2022-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=200, null=True),
        ),
    ]
