# Generated by Django 4.1.3 on 2022-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='request_status',
            field=models.CharField(choices=[('empty', 'empty'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='empty', max_length=200, null=True),
        ),
    ]
