# Generated by Django 4.1.3 on 2022-12-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='request_status',
        ),
    ]
