# Generated by Django 4.1.3 on 2022-12-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='sender',
        ),
    ]
